### ISSUE TITLE
It might be useful to define hierarchical permissions

### ISSUE THREAD

**Issue by qina83** [LeandroLuccerini/simple-access-control#7]
Scenario:
How to define permissions for admin role. Should I define every single permission?

I would like to define permission hierarchically:
`new Permission(new Action('product'), true)`
`new Permission(new Action('product.detail'), true)`
`new Permission(new Action('product.detail.view'), true)`

* first permission allows every action on `product`
* second one allows every action on `product.detail`
* third allows just `view` action on `product.detail`

Then the admin will have all the permissions on the `product` (present and future) in an easy way.
This could be useful also to define permissions for other backoffice roles.

**Comment by LeandroLuccerini** [comment]
Interesting feature, thank you.
I was thinking on how make less aleatory the choice of the structure of the label. In this case is dot-separated, but how to introduce a validation of the right model used? Is it necessary?

**Comment by LeandroLuccerini** [comment]
@qina83 please take a look at the solution proposed in [feature/Hierarchical_permissions](https://github.com/LeandroLuccerini/simple-access-control/tree/feature/Hierarchical_permissions)
